[fmt]
line_length = 80
tab_width = 2
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"

[profile.default]
src = "src"
out = "out"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config